version: "3.9"  # optional since v1.27.0
services:
  app:
    container_name: task-manager
    build:
      context: .
      dockerfile: Dockerfile
    image: devjonte/task-manager:1.0.0
    restart: always
    ports:
      - "44397:80"
    privileged: true
    networks:
      - task-manager-network
    volumes:
      - task-manager-volume:/app/data
volumes:
  task-manager-volume:
networks:
  task-manager-network:
    driver: bridge
