version: "3.9"  # optional since v1.27.0
services:
  app:
    container_name: task-manager
    environment:
      - TZ=America/Chicago
    build:
      context: .
      dockerfile: Dockerfile
    image: devjonte/task-manager:1.0.0
    restart: always
    container_name: dotnet-minimal-api-entity-framework-sqlite
    ports:
      - "44397:80"
    privileged: true
    networks:
      - mountainclimber
    volumes:
      - data-volume:/app/data
volumes:
  data-volume:      
networks:
      mountainclimber:
        driver: bridge